#!/usr/bin/env node
var path = require('path')
var parse = require('minimist')
var browserify = require('browserify')
var path = require('path')
var args = parse(process.argv)
var entries = args.e.split(',') || args.entries.split(',')
var output = args.o || args.output
var main = args.m || args.main
var url = args.url || ''
var options = {
    main: main,
    map: {},
    output: output,
    url: url
}
entries.forEach(f=> {
  // We need to treat the entry file differently. You can't expose an alias for it.
  if (f === main) {
    console.info('require:', f)
    console.info('output:', 'entry.js')
    console.info('remote:', url+'/'+'entry.js\n')
    // Going to hard code entry.js because works.
    options.map['entry.js'] = [f]
  } else {
    console.info('require:', f)
    console.info('output:', output+'/'+f.split('/').pop())
    console.info('expose:', f.split('/').pop().replace('.js', ''), '\n')
    console.info('remote:', url+'/'+f.split('/').pop()+'\n')
    options.map[f.split('/').pop()] = [{
      require: f,
      expose: f.split('/').pop().replace('.js', '')
    }]
  }
})

console.info('partitioning bundle with options:\n', options)

var b = browserify()
b.plugin('partition-bundle', options)
b.transform('yo-yoify', {global: true})
b.bundle()
